### ISSUE TITLE
Flaky end-to-end tests

### ISSUE THREAD

**Issue by rebecca-butler** [ros2/domain_bridge#46]
Some of the tests in `test_domain_bridge_end_to_end.cpp` fail occasionally when running `colcon test`:

```
- domain_bridge.TestDomainBridgeEndToEnd compress_mode
  <<< failure message
    /home/rebecca/ws/domain_bridge_ws/domain_bridge/test/domain_bridge/test_domain_bridge_end_to_end.cpp:216
    Value of: poll_condition([&got_message]() {return got_message.load();}, 3s)
      Actual: false
    Expected: true
  >>>
```

I've seen messages like this for the `compress_mode`, `decompress_mode`, and `remap_topic_name` tests.

**Comment by jacobperron** [comment]
@ivanpauno Any ideas about what's happening here?

**Comment by jacobperron** [comment]
If `sub->get_publisher_count() == 1u` does it guarantee that the subscription will receive the one published message?

**Comment by ivanpauno** [comment]
mmm, maybe we also have to wait until `pub->get_subscription_count()` is the correct number of subscriptions (?).
If both conditions are satisfied I would expect the message to always arrive
